#!/bin/sh
rm build/* 2> /dev/null
set -e
echo "building"
arm-none-eabi-as -g -mcpu=cortex-m4  -o build/blink.o blink.s
arm-none-eabi-ld -T layout.ld -o build/blink.elf build/blink.o
arm-none-eabi-objcopy -O ihex -R .eeprom build/blink.elf build/blink.hex
echo "build complete"
echo "ready to upload, press reset on Teensy"
teensy_loader_cli -w --mcu=mk64fx512 build/blink.hex
#arm-none-eabi-objdump -d  build/blink.elf
